// tokenPurchaseWithStripe
ledgerEvent = {
  "ResponseMetadata": {
    "RequestId": "PCHE7MLGPPGXYGWDEO22YZ7NBDRVFNPD14Z2UR15O2SAEKUY2M9D"
  },
  "Messages": [
    {
      "MessageId": "79e4b89c-9191-4450-8955-668c1930aaa4",
      "ReceiptHandle": "MThiZmQ1NDYtNjg5OS00MTM3LWFhMWMtN2E1OGYzODg3YmQ1IGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6dGVzdCA3OWU0Yjg5Yy05MTkxLTQ0NTAtODk1NS02NjhjMTkzMGFhYTQgMTY2NjYxMzM2OS45MTM1ODk1",
      "MD5OfBody": "50ea3532538d9683ae32ca4b12123313",
      "Body": {
        "version": "0",
        "id": "777bc233-6169-463d-90f5-8261d3c8ce39",
        "detail-type": "tokenPurchaseWithStripe",
        "source": "original-works.evm-transaction-sender",
        "account": "000000000000",
        "time": "2022-10-24T11:58:15Z",
        "region": "us-east-1",
        "resources": [],
        "detail": {
          "origin": "payment-service-token-purchase",
          "eventMetadata": {
            "id": "goZuC2SsgB2Lfs",
            "userSub": "802788de-539c-4abb-8d71-a93851197d35",
            "invoiceItemId": "ii_Q0ScLCttVgHGGG",
            "invoiceId": "in_gHU0ASc6Qp8S99",
            "currency": "usd",
            "subgraphItemId": "0x09142C6Bba0548140B5d9C6811729994896660b9-1",
            "quantity": 62,
            "createdAt": "2022-08-13T12:49:40.118Z"
          },
          "eventRawData": {
            "customer": {
              "id": "cus_5imgzoCoMkGduV",
              "object": "customer",
              "address": null,
              "balance": 0,
              "created": 1424217077,
              "currency": "usd",
              "default_currency": "usd",
              "default_source": "card_15XL7Z2eZvKYlo2CaLsb58gg",
              "delinquent": true,
              "description": null,
              "discount": null,
              "email": null,
              "invoice_prefix": "E42E59B",
              "invoice_settings": {
                "custom_fields": null,
                "default_payment_method": null,
                "footer": null,
                "rendering_options": null
              },
              "livemode": false,
              "metadata": {},
              "name": null,
              "next_invoice_sequence": 65179,
              "phone": null,
              "preferred_locales": [],
              "shipping": null,
              "tax_exempt": "none",
              "test_clock": null
            },
            "invoice": {
              "id": "in_1Chdoz4EUb4Hd4km09jsbyjI",
              "object": "invoice",
              "account_country": "US",
              "account_name": "Stripe.com",
              "account_tax_ids": null,
              "amount_due": 1000,
              "amount_paid": 0,
              "amount_remaining": 1000,
              "application": null,
              "application_fee_amount": null,
              "attempt_count": 0,
              "attempted": false,
              "auto_advance": true,
              "automatic_tax": {
                "enabled": false,
                "status": null
              },
              "billing_reason": "manual",
              "charge": null,
              "collection_method": "charge_automatically",
              "created": 1659437566,
              "currency": "usd",
              "custom_fields": null,
              "customer": "cus_5imgzoCoMkGduV",
              "customer_address": null,
              "customer_email": null,
              "customer_name": null,
              "customer_phone": null,
              "customer_shipping": null,
              "customer_tax_exempt": "none",
              "customer_tax_ids": [],
              "default_payment_method": null,
              "default_source": null,
              "default_tax_rates": [],
              "description": null,
              "discount": null,
              "discounts": [],
              "due_date": null,
              "ending_balance": null,
              "footer": null,
              "hosted_invoice_url": null,
              "invoice_pdf": null,
              "last_finalization_error": null,
              "lines": {
                "object": "list",
                "data": [
                  {
                    "id": "il_1LSIiQ2eZvKYlo2CnUEwvFkq",
                    "object": "line_item",
                    "amount": 1000,
                    "amount_excluding_tax": 1000,
                    "currency": "usd",
                    "description": "My First Invoice Item (created for API docs)",
                    "discount_amounts": [],
                    "discountable": true,
                    "discounts": [],
                    "invoice_item": "ii_1LSIiQ2eZvKYlo2CQti9N7ko",
                    "livemode": false,
                    "metadata": {},
                    "period": {
                      "end": 1659437566,
                      "start": 1659437566
                    },
                    "price": {
                      "id": "price_1LSIYv2eZvKYlo2CmVT7nEC8",
                      "object": "price",
                      "active": true,
                      "billing_scheme": "per_unit",
                      "created": 1659436977,
                      "currency": "usd",
                      "custom_unit_amount": null,
                      "livemode": false,
                      "lookup_key": null,
                      "metadata": {},
                      "nickname": null,
                      "product": "prod_MAdqztrfo2dTKY",
                      "recurring": null,
                      "tax_behavior": "unspecified",
                      "tiers_mode": null,
                      "transform_quantity": null,
                      "type": "one_time",
                      "unit_amount": 1000,
                      "unit_amount_decimal": "1000"
                    },
                    "proration": false,
                    "proration_details": {
                      "credited_items": null
                    },
                    "quantity": 1,
                    "subscription": null,
                    "tax_amounts": [],
                    "tax_rates": [],
                    "type": "invoiceitem",
                    "unit_amount_excluding_tax": "1000"
                  }
                ],
                "has_more": false,
                "url": "/v1/invoices/in_1LSIiQ2eZvKYlo2CcQ7Z5c1V/lines"
              },
              "livemode": false,
              "metadata": {},
              "next_payment_attempt": 1659441166,
              "number": null,
              "on_behalf_of": null,
              "paid": false,
              "paid_out_of_band": false,
              "payment_intent": null,
              "payment_settings": {
                "default_mandate": null,
                "payment_method_options": null,
                "payment_method_types": null
              },
              "period_end": 1662109085,
              "period_start": 1659430685,
              "post_payment_credit_notes_amount": 0,
              "pre_payment_credit_notes_amount": 0,
              "quote": null,
              "receipt_number": null,
              "redaction": null,
              "rendering_options": null,
              "starting_balance": 0,
              "statement_descriptor": null,
              "status": "draft",
              "status_transitions": {
                "finalized_at": null,
                "marked_uncollectible_at": null,
                "paid_at": null,
                "voided_at": null
              },
              "subscription": null,
              "subtotal": 1000,
              "subtotal_excluding_tax": 1000,
              "tax": null,
              "test_clock": null,
              "total": 1000,
              "total_discount_amounts": [],
              "total_excluding_tax": 1000,
              "total_tax_amounts": [],
              "transfer_data": null,
              "webhooks_delivered_at": null
            },
            "invoiceItem": {
              "id": "ii_1EuJSK4EUb4Hd4kmkMx2TsIl",
              "object": "invoiceitem",
              "amount": 300,
              "currency": "usd",
              "customer": "cus_5imgzoCoMkGduV",
              "date": 1658903206,
              "description": "auto topup addtional_viewer",
              "discountable": true,
              "discounts": [],
              "invoice": null,
              "livemode": false,
              "metadata": {},
              "period": {
                "end": 1658903206,
                "start": 1658903206
              },
              "price": {
                "id": "price_1LQ23A2eZvKYlo2C0BjIm2lx",
                "object": "price",
                "active": true,
                "billing_scheme": "per_unit",
                "created": 1658896848,
                "currency": "usd",
                "custom_unit_amount": null,
                "livemode": false,
                "lookup_key": null,
                "metadata": {},
                "nickname": null,
                "product": "prod_M8IeT0KigtshO3",
                "recurring": null,
                "tax_behavior": "unspecified",
                "tiers_mode": null,
                "transform_quantity": null,
                "type": "one_time",
                "unit_amount": 300,
                "unit_amount_decimal": "300"
              },
              "proration": false,
              "quantity": 1,
              "subscription": null,
              "tax_rates": [],
              "test_clock": null,
              "unit_amount": 300,
              "unit_amount_decimal": "300"
            }
          }
        }
      }
    }
  ]
}

